services:
  auth:
    build:
      context: ..
      dockerfile: auth/Dockerfile
    container_name: copy-city-auth
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    command: [
      "sh",
      "-c",
      "alembic upgrade head && python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ]
    volumes:
      - ./src:/app/auth/src
    networks:
      - copy-city-network

networks:
  copy-city-network:
    external: true
    name: copy-city-network
