"""init backend schema

Revision ID: 1da3ac6c7fac
Revises: 
Create Date: 2026-05-10 14:51:19.382508

"""
import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1da3ac6c7fac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.Enum('page', 'piece', 'photo', 'order', 'hour', name='product_unit', schema='backend'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=datetime.timezone(datetime.timedelta(seconds=10800))), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=datetime.timezone(datetime.timedelta(seconds=10800))), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='backend'
    )
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('new', 'in_progress', 'done', 'cancelled', name='order_status', schema='backend'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=datetime.timezone(datetime.timedelta(seconds=10800))), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=datetime.timezone(datetime.timedelta(seconds=10800))), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='backend'
    )
    op.create_table('photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=datetime.timezone(datetime.timedelta(seconds=10800))), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=datetime.timezone(datetime.timedelta(seconds=10800))), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['backend.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='backend'
    )
    op.create_table('order_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['backend.orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['backend.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='backend'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item', schema='backend')
    op.drop_table('photos', schema='backend')
    op.drop_table('orders', schema='backend')
    op.drop_table('products', schema='backend')
    # ### end Alembic commands ###
